### ISSUE TITLE
Attempt to index field 'bo' (a nil value)

### ISSUE THREAD

**Issue by psamim** [ttys3/nvim-blamer.lua#1]
Hi,

I get the following error and see no git blame info.

![image](https://user-images.githubusercontent.com/1868679/102686593-f9e50800-41fd-11eb-91d4-843dd619cda8.png)

Thanks

**Comment by ttys3** [comment]
can you describe how to re-produce the issue?

**Comment by psamim** [comment]
@ttys3 I added this line to my .vimrc:
```
Plug 'ttys3/nvim-blamer.lua'
```
Then run `PlugInstall`

I see the error when opening files.

**Comment by japorized** [comment]
Just tried it using the built-in package manager. Same error shows up right after adding the plugin, without further customization.

**Comment by ttys3** [comment]
@japorized  which neovim version are you using?

this plugin need a nightly version of neovim

**Comment by japorized** [comment]
Oh, apologies then. I'm not on nightly. Thank you for the info.

Perhaps we should add this as a note in the README?

**Comment by ttys3** [comment]
> Oh, apologies then. I'm not on nightly. Thank you for the info.
> 
> Perhaps we should add this as a note in the README?

done  https://github.com/ttys3/nvim-blamer.lua/commit/01476886959babdf6d15745aa8cb94fd80db7e91
