### ISSUE TITLE
Toggle/Auto commands problem.

### ISSUE THREAD

**Issue by mthnglac** [ttys3/nvim-blamer.lua#5]
First of all, I liked the plugin very much and it was very successful. However, there are a few things I want to share:
* I cannot activate the plugin with "NvimBlamerToggle". I have to run the "NvimBlamerAuto" command before and then close it with "NvimBlamerToggle".
* Suggestion: This came to my mind; I thought it would be better if there were only "NvimBlamerEnable", "NvimBlamerDisable", "NvimBlamerToggle" commands and the "auto" scenario was managed from within the configuration. Because I would like to manage such a logic from the configuration.

**Comment by ttys3** [comment]
yes, you are right. the `auto` should be user config part.

both are just wrapper to lua code:


```vim
function! nvimblamer#auto() abort
  augroup BlamerLua
    autocmd CursorHold   * lua require'nvim-blamer'.show()
    autocmd CursorMoved  * lua require'nvim-blamer'.clear()
    autocmd CursorMovedI * lua require'nvim-blamer'.clear()
  augroup end
endfunction

function! nvimblamer#toggle() abort
  lua require'nvim-blamer'.toggle()
endfunction
```

`NvimBlamerAuto()` is just for user to enable the plugin fast, and it is not necessary.

Maybe should mark as `deprecated`, because remove it directly will break exists user's config.

**Comment by mthnglac** [comment]
I did not fully understand what to do. Do you want to think of something about the feature that I mentioned, or will it continue as it is now?
